--========됨==========
INSERT INTO STAFF(STAFF_NO, STAFF_NAME, JUMIN_NO, SCHOOL_CODE, DEPARTMENT_CODE, GRADUATE_DAY) 
VALUES(
	STAFF_SEQ.NEXTVAL, 
	'유재욱', 
	'000202-2000000',
	(SELECT SCHOOL_CODE FROM CODE_SCHOOL cs WHERE SCHOOL_NAME = '일반대졸'),
	(SELECT DEPARTMENT_CODE FROM CODE_DEPARTMENT cd WHERE DEPARTMENT_NAME = 'SI사업부'),
	TO_DATE('20000228','YYYY-MM-DD')
	);
	
SELECT * FROM STAFF_SKILL ss;

--========됨==========
INSERT INTO STAFF_SKILL(STAFF_SKILL_NO, STAFF_NO, SKILL_CODE)
VALUES(
	STAFF_SKILL_SEQ.NEXTVAL,
	(SELECT STAFF_NO FROM STAFF WHERE STAFF_NAME='유재욱'),
	(SELECT SKILL_CODE FROM CODE_SKILL cs WHERE SKILL_NAME='JSP') --FOR문돌려야함
	);
	
--========됨==========
UPDATE STAFF SET 
STAFF_NAME='유성룡',
JUMIN_NO='000303-1000000',
SCHOOL_CODE= (SELECT SCHOOL_CODE FROM CODE_SCHOOL cs WHERE SCHOOL_NAME = '일반대졸'),
DEPARTMENT_CODE = (SELECT DEPARTMENT_CODE FROM CODE_DEPARTMENT cd WHERE DEPARTMENT_NAME = '컨설팅사업부')
WHERE STAFF_NAME='유재욱'
AND JUMIN_NO='000202-2000000';



--==============안됨? 됨? 됨
UPDATE STAFF_SKILL SET 
SKILL_CODE = (SELECT SKILL_CODE FROM CODE_SKILL cs WHERE SKILL_NAME = 'PHP')
WHERE STAFF_NO= (SELECT STAFF_NO FROM STAFF WHERE STAFF_NAME='유성룡' AND JUMIN_NO='000303-1000000');
